---
- name: Set up this machine
  hosts: devapps

  tasks:

  - name: Install apt latest packages
    become: yes
    become_user: root
    ansible.builtin.apt:
      state: latest
      update_cache: true
      name:
      - tmux
      # Besides installing this package, you need to incorporate it into your bash shell.
      # https://direnv.net/docs/hook.html
      - direnv
      # Pyenv packages for building pythons
      # https://github.com/pyenv/pyenv/blob/6e3b91a816e5551d646211b71749addffefb0c15/README.md?plain=1#L379-L384
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - curl
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev

  - name: Install snaps
    become: yes
    become_user: root
    community.general.snap:
      name:
      - tldr

  - name: Install classic snaps
    become: yes
    become_user: root
    community.general.snap:
      # We use classic to deactivate the restricted environment that snaps normally run in.
      # This is normal for IDE's, which need generous access to the host machine.
      classic: true
      name:
      - nvim

  - name: Install pyenv
    ansible.builtin.git:
      repo: https://github.com/pyenv/pyenv.git
      dest: /home/josalvatorre/.pyenv

  - name: Install personal NeoVim config
    become: yes
    become_user: root
    ansible.builtin.git:
      repo: https://github.com/josalvatorre/personal-nvim-config
      dest: /home/josalvatorre/.config/nvim
      # This repo was forked from NvChad. The default branch is v2.0.
      version: v3.0
