# https://ansible.readthedocs.io/projects/builder/en/stable/definition/
# https://ansible.readthedocs.io/en/latest/getting_started_ee/build_execution_environment.html

version: 3

images:
  base_image:
    # I'd prefer Ubuntu, but the maintainers primarily support RHEL distros.
    # Getting Ubuntu to work was a nightmare.
    name: quay.io/fedora/fedora:latest
dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  python_interpreter:
    package_system: "python310"
    python_path: "/usr/bin/python3.10"
