---
- name: Set up my local Mac
  hosts: mymac

  tasks:

  - name: Install Homebrew packages
    community.general.homebrew:
      update_homebrew: true
      upgrade_all: true
      name:
      - 1password-cli
      - gh
      - tree
    # Homebrew print a warning if the package is already installed when you try to upgrade.
    # Unfortunately, the Ansible module sees this as an error and fails.
    # The following hack is meant to mitigate that.
    register: homebrew_result
    failed_when:
      - homebrew_result.failed
      - "'Warning: Not upgrading' not in homebrew_result.msg"
